"""initial schema

Revision ID: f5d71a1504bb
Revises: 
Create Date: 2026-04-03 22:28:39.789095

"""
from alembic import op
from pgvector.sqlalchemy import VECTOR
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5d71a1504bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('canonical_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('active_version_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('cleaned_markdown', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_content_hash'), ['content_hash'], unique=False)

    op.create_foreign_key(
        'fk_documents_active_version_id',
        'documents',
        'document_versions',
        ['active_version_id'],
        ['id'],
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('retrieved_chunk_ids', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('retrieval_debug_json', sa.JSON(), nullable=False),
    sa.Column('answer_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_version_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('heading_path', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('prev_chunk_id', sa.String(), nullable=True),
    sa.Column('next_chunk_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embedding', VECTOR(dim=3072), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunks_document_version_chunk_index', ['document_version_id', 'chunk_index'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_chunks_document_version_chunk_index')

    op.drop_table('chunks')
    op.drop_table('query_logs')
    op.drop_table('ingestion_jobs')
    op.drop_constraint('fk_documents_active_version_id', 'documents', type_='foreignkey')
    op.drop_table('documents')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_content_hash'))

    op.drop_table('document_versions')
    # ### end Alembic commands ###
